// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PowerFit.Models;

namespace PowerFit.Migrations
{
    [DbContext(typeof(PowerFitContext))]
    [Migration("20220420084505_DataPopulation")]
    partial class DataPopulation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PowerFit.Models.Exercise", b =>
                {
                    b.Property<int>("ExerciseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnglishExerciseName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExerciseName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExerciseTypeId")
                        .HasColumnType("int");

                    b.Property<byte[]>("Image")
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ExerciseId");

                    b.HasIndex("ExerciseTypeId");

                    b.ToTable("Exercises");

                    b.HasData(
                        new
                        {
                            ExerciseId = 1,
                            Description = "",
                            EnglishExerciseName = "Back squat",
                            ExerciseName = "Stražnji čučanj",
                            ExerciseTypeId = 1,
                            InsertDate = new DateTime(2022, 4, 20, 10, 45, 5, 185, DateTimeKind.Local).AddTicks(8570),
                            IsDeleted = false
                        },
                        new
                        {
                            ExerciseId = 2,
                            Description = "",
                            EnglishExerciseName = "Front squat",
                            ExerciseName = "Prednji čučanj",
                            ExerciseTypeId = 1,
                            InsertDate = new DateTime(2022, 4, 20, 10, 45, 5, 196, DateTimeKind.Local).AddTicks(1679),
                            IsDeleted = false
                        },
                        new
                        {
                            ExerciseId = 3,
                            Description = "",
                            EnglishExerciseName = "Lunge",
                            ExerciseName = "Iskorak",
                            ExerciseTypeId = 1,
                            InsertDate = new DateTime(2022, 4, 20, 10, 45, 5, 196, DateTimeKind.Local).AddTicks(1737),
                            IsDeleted = false
                        },
                        new
                        {
                            ExerciseId = 4,
                            Description = "",
                            EnglishExerciseName = "Pullup",
                            ExerciseName = "Zgib",
                            ExerciseTypeId = 1,
                            InsertDate = new DateTime(2022, 4, 20, 10, 45, 5, 196, DateTimeKind.Local).AddTicks(1744),
                            IsDeleted = false
                        },
                        new
                        {
                            ExerciseId = 5,
                            Description = "",
                            EnglishExerciseName = "Barbell row",
                            ExerciseName = "Veslanje u natklonu",
                            ExerciseTypeId = 1,
                            InsertDate = new DateTime(2022, 4, 20, 10, 45, 5, 196, DateTimeKind.Local).AddTicks(1750),
                            IsDeleted = false
                        },
                        new
                        {
                            ExerciseId = 6,
                            Description = "",
                            EnglishExerciseName = "Dumbbell row",
                            ExerciseName = "Veslanje sa bučicom",
                            ExerciseTypeId = 1,
                            InsertDate = new DateTime(2022, 4, 20, 10, 45, 5, 196, DateTimeKind.Local).AddTicks(1753),
                            IsDeleted = false
                        },
                        new
                        {
                            ExerciseId = 7,
                            Description = "",
                            EnglishExerciseName = "Conventional deadlift",
                            ExerciseName = "Konvencionalno mrtvo dizanje",
                            ExerciseTypeId = 1,
                            InsertDate = new DateTime(2022, 4, 20, 10, 45, 5, 196, DateTimeKind.Local).AddTicks(1757),
                            IsDeleted = false
                        },
                        new
                        {
                            ExerciseId = 8,
                            Description = "",
                            EnglishExerciseName = "Sumo deadlift",
                            ExerciseName = "Sumo mrtvo dizanje",
                            ExerciseTypeId = 1,
                            InsertDate = new DateTime(2022, 4, 20, 10, 45, 5, 196, DateTimeKind.Local).AddTicks(1762),
                            IsDeleted = false
                        },
                        new
                        {
                            ExerciseId = 9,
                            Description = "",
                            EnglishExerciseName = "Romanian deadlift",
                            ExerciseName = "Rumunjsko mrtvo dizanje",
                            ExerciseTypeId = 1,
                            InsertDate = new DateTime(2022, 4, 20, 10, 45, 5, 196, DateTimeKind.Local).AddTicks(1831),
                            IsDeleted = false
                        },
                        new
                        {
                            ExerciseId = 10,
                            Description = "",
                            EnglishExerciseName = "Overhead triceps extension",
                            ExerciseName = "Triceps ekstenzija iznad glave",
                            ExerciseTypeId = 2,
                            InsertDate = new DateTime(2022, 4, 20, 10, 45, 5, 196, DateTimeKind.Local).AddTicks(1835),
                            IsDeleted = false
                        },
                        new
                        {
                            ExerciseId = 11,
                            Description = "",
                            EnglishExerciseName = "Skullcrusher",
                            ExerciseName = "Potisak s čela na ravnoj klupi",
                            ExerciseTypeId = 2,
                            InsertDate = new DateTime(2022, 4, 20, 10, 45, 5, 196, DateTimeKind.Local).AddTicks(1840),
                            IsDeleted = false
                        },
                        new
                        {
                            ExerciseId = 12,
                            Description = "",
                            EnglishExerciseName = "Dips",
                            ExerciseName = "Paralelno prodapadnje",
                            ExerciseTypeId = 1,
                            InsertDate = new DateTime(2022, 4, 20, 10, 45, 5, 196, DateTimeKind.Local).AddTicks(1843),
                            IsDeleted = false
                        },
                        new
                        {
                            ExerciseId = 13,
                            Description = "",
                            EnglishExerciseName = "Barbell curl",
                            ExerciseName = "Stojeći pregib sa šipkom",
                            ExerciseTypeId = 2,
                            InsertDate = new DateTime(2022, 4, 20, 10, 45, 5, 196, DateTimeKind.Local).AddTicks(1847),
                            IsDeleted = false
                        },
                        new
                        {
                            ExerciseId = 14,
                            Description = "",
                            EnglishExerciseName = "Dumbbell curl",
                            ExerciseName = "Pregib s bučicama",
                            ExerciseTypeId = 2,
                            InsertDate = new DateTime(2022, 4, 20, 10, 45, 5, 196, DateTimeKind.Local).AddTicks(1851),
                            IsDeleted = false
                        },
                        new
                        {
                            ExerciseId = 15,
                            Description = "",
                            EnglishExerciseName = "Hammer curl",
                            ExerciseName = "Pregib bučicama sa neutralnim hvatom",
                            ExerciseTypeId = 2,
                            InsertDate = new DateTime(2022, 4, 20, 10, 45, 5, 196, DateTimeKind.Local).AddTicks(1855),
                            IsDeleted = false
                        },
                        new
                        {
                            ExerciseId = 16,
                            Description = "",
                            EnglishExerciseName = "Upright row",
                            ExerciseName = "Okomito veslanje",
                            ExerciseTypeId = 1,
                            InsertDate = new DateTime(2022, 4, 20, 10, 45, 5, 196, DateTimeKind.Local).AddTicks(1859),
                            IsDeleted = false
                        },
                        new
                        {
                            ExerciseId = 17,
                            Description = "",
                            EnglishExerciseName = "Overhead press",
                            ExerciseName = "Potisak iznad glave",
                            ExerciseTypeId = 1,
                            InsertDate = new DateTime(2022, 4, 20, 10, 45, 5, 196, DateTimeKind.Local).AddTicks(1863),
                            IsDeleted = false
                        },
                        new
                        {
                            ExerciseId = 18,
                            Description = "",
                            EnglishExerciseName = "Behind the neck press",
                            ExerciseName = "Potisak iza glave",
                            ExerciseTypeId = 1,
                            InsertDate = new DateTime(2022, 4, 20, 10, 45, 5, 196, DateTimeKind.Local).AddTicks(1867),
                            IsDeleted = false
                        },
                        new
                        {
                            ExerciseId = 19,
                            Description = "",
                            EnglishExerciseName = "Lateral raise",
                            ExerciseName = "Lateralno podizanje",
                            ExerciseTypeId = 2,
                            InsertDate = new DateTime(2022, 4, 20, 10, 45, 5, 196, DateTimeKind.Local).AddTicks(1874),
                            IsDeleted = false
                        },
                        new
                        {
                            ExerciseId = 20,
                            Description = "",
                            EnglishExerciseName = "Flat bench press",
                            ExerciseName = "Potisak sa ravne klupe",
                            ExerciseTypeId = 1,
                            InsertDate = new DateTime(2022, 4, 20, 10, 45, 5, 196, DateTimeKind.Local).AddTicks(1878),
                            IsDeleted = false
                        },
                        new
                        {
                            ExerciseId = 21,
                            Description = "",
                            EnglishExerciseName = "Incline bench press",
                            ExerciseName = "Potisak sa kose klupe",
                            ExerciseTypeId = 1,
                            InsertDate = new DateTime(2022, 4, 20, 10, 45, 5, 196, DateTimeKind.Local).AddTicks(1882),
                            IsDeleted = false
                        },
                        new
                        {
                            ExerciseId = 22,
                            Description = "",
                            EnglishExerciseName = "Flat dumbbell flys",
                            ExerciseName = "Razvlačenje bučicama na ravnoj klupi",
                            ExerciseTypeId = 2,
                            InsertDate = new DateTime(2022, 4, 20, 10, 45, 5, 196, DateTimeKind.Local).AddTicks(1886),
                            IsDeleted = false
                        },
                        new
                        {
                            ExerciseId = 23,
                            Description = "",
                            EnglishExerciseName = "Plank",
                            ExerciseName = "Plank",
                            ExerciseTypeId = 3,
                            InsertDate = new DateTime(2022, 4, 20, 10, 45, 5, 196, DateTimeKind.Local).AddTicks(1889),
                            IsDeleted = false
                        },
                        new
                        {
                            ExerciseId = 24,
                            Description = "",
                            EnglishExerciseName = "Side plank",
                            ExerciseName = "Bočni plank",
                            ExerciseTypeId = 3,
                            InsertDate = new DateTime(2022, 4, 20, 10, 45, 5, 196, DateTimeKind.Local).AddTicks(1894),
                            IsDeleted = false
                        },
                        new
                        {
                            ExerciseId = 25,
                            Description = "",
                            EnglishExerciseName = "V-situps",
                            ExerciseName = "V-podizanja",
                            ExerciseTypeId = 2,
                            InsertDate = new DateTime(2022, 4, 20, 10, 45, 5, 196, DateTimeKind.Local).AddTicks(1897),
                            IsDeleted = false
                        },
                        new
                        {
                            ExerciseId = 30,
                            Description = "",
                            EnglishExerciseName = "Neck curl",
                            ExerciseName = "Fleksija vrata",
                            ExerciseTypeId = 2,
                            InsertDate = new DateTime(2022, 4, 20, 10, 45, 5, 196, DateTimeKind.Local).AddTicks(1901),
                            IsDeleted = false
                        },
                        new
                        {
                            ExerciseId = 31,
                            Description = "",
                            EnglishExerciseName = "Neck extension",
                            ExerciseName = "Ekstenzija vrata",
                            ExerciseTypeId = 2,
                            InsertDate = new DateTime(2022, 4, 20, 10, 45, 5, 196, DateTimeKind.Local).AddTicks(1905),
                            IsDeleted = false
                        },
                        new
                        {
                            ExerciseId = 32,
                            Description = "",
                            EnglishExerciseName = "Wrist curl",
                            ExerciseName = "Pregib zapešća",
                            ExerciseTypeId = 2,
                            InsertDate = new DateTime(2022, 4, 20, 10, 45, 5, 196, DateTimeKind.Local).AddTicks(1939),
                            IsDeleted = false
                        },
                        new
                        {
                            ExerciseId = 33,
                            Description = "",
                            EnglishExerciseName = "Reverse wrist curl",
                            ExerciseName = "Obrnuti pregib zapešća",
                            ExerciseTypeId = 2,
                            InsertDate = new DateTime(2022, 4, 20, 10, 45, 5, 196, DateTimeKind.Local).AddTicks(1943),
                            IsDeleted = false
                        },
                        new
                        {
                            ExerciseId = 34,
                            Description = "",
                            EnglishExerciseName = "Pronation",
                            ExerciseName = "Pronacija zapešća",
                            ExerciseTypeId = 2,
                            InsertDate = new DateTime(2022, 4, 20, 10, 45, 5, 196, DateTimeKind.Local).AddTicks(1947),
                            IsDeleted = false
                        },
                        new
                        {
                            ExerciseId = 35,
                            Description = "",
                            EnglishExerciseName = "Supination",
                            ExerciseName = "Supinacija zapešća",
                            ExerciseTypeId = 2,
                            InsertDate = new DateTime(2022, 4, 20, 10, 45, 5, 196, DateTimeKind.Local).AddTicks(1950),
                            IsDeleted = false
                        },
                        new
                        {
                            ExerciseId = 36,
                            Description = "",
                            EnglishExerciseName = "Standing calf raise",
                            ExerciseName = "Stojeće podizanje listova",
                            ExerciseTypeId = 2,
                            InsertDate = new DateTime(2022, 4, 20, 10, 45, 5, 196, DateTimeKind.Local).AddTicks(1954),
                            IsDeleted = false
                        },
                        new
                        {
                            ExerciseId = 37,
                            Description = "",
                            EnglishExerciseName = "Seated calf raise",
                            ExerciseName = "Sjedeće podizanje listova",
                            ExerciseTypeId = 2,
                            InsertDate = new DateTime(2022, 4, 20, 10, 45, 5, 196, DateTimeKind.Local).AddTicks(1958),
                            IsDeleted = false
                        },
                        new
                        {
                            ExerciseId = 38,
                            Description = "",
                            EnglishExerciseName = "Leg press calf raise",
                            ExerciseName = "Podizanje listova na nožnoj preši",
                            ExerciseTypeId = 2,
                            InsertDate = new DateTime(2022, 4, 20, 10, 45, 5, 196, DateTimeKind.Local).AddTicks(1963),
                            IsDeleted = false
                        },
                        new
                        {
                            ExerciseId = 39,
                            Description = "",
                            EnglishExerciseName = "Farmers walk",
                            ExerciseName = "Farmerov hod",
                            ExerciseTypeId = 1,
                            InsertDate = new DateTime(2022, 4, 20, 10, 45, 5, 196, DateTimeKind.Local).AddTicks(1967),
                            IsDeleted = false
                        },
                        new
                        {
                            ExerciseId = 40,
                            Description = "",
                            EnglishExerciseName = "Log clean and press",
                            ExerciseName = "Log nabačaj i potisak",
                            ExerciseTypeId = 1,
                            InsertDate = new DateTime(2022, 4, 20, 10, 45, 5, 196, DateTimeKind.Local).AddTicks(1971),
                            IsDeleted = false
                        },
                        new
                        {
                            ExerciseId = 41,
                            Description = "",
                            EnglishExerciseName = "Yoke walk",
                            ExerciseName = "Yoke hod",
                            ExerciseTypeId = 1,
                            InsertDate = new DateTime(2022, 4, 20, 10, 45, 5, 196, DateTimeKind.Local).AddTicks(1975),
                            IsDeleted = false
                        },
                        new
                        {
                            ExerciseId = 42,
                            Description = "",
                            EnglishExerciseName = "Clean and press",
                            ExerciseName = "Nabačaj i potisak",
                            ExerciseTypeId = 1,
                            InsertDate = new DateTime(2022, 4, 20, 10, 45, 5, 196, DateTimeKind.Local).AddTicks(1978),
                            IsDeleted = false
                        },
                        new
                        {
                            ExerciseId = 43,
                            Description = "",
                            EnglishExerciseName = "Clean and jerk",
                            ExerciseName = "Nabačaj i izbačaj",
                            ExerciseTypeId = 1,
                            InsertDate = new DateTime(2022, 4, 20, 10, 45, 5, 196, DateTimeKind.Local).AddTicks(1982),
                            IsDeleted = false
                        },
                        new
                        {
                            ExerciseId = 44,
                            Description = "",
                            EnglishExerciseName = "Tabata",
                            ExerciseName = "Tabata",
                            ExerciseTypeId = 1,
                            InsertDate = new DateTime(2022, 4, 20, 10, 45, 5, 196, DateTimeKind.Local).AddTicks(1986),
                            IsDeleted = false
                        },
                        new
                        {
                            ExerciseId = 45,
                            Description = "",
                            EnglishExerciseName = "Rowing machine",
                            ExerciseName = "Sprava za veslanje",
                            ExerciseTypeId = 1,
                            InsertDate = new DateTime(2022, 4, 20, 10, 45, 5, 196, DateTimeKind.Local).AddTicks(1990),
                            IsDeleted = false
                        },
                        new
                        {
                            ExerciseId = 46,
                            Description = "",
                            EnglishExerciseName = "Stationary bike",
                            ExerciseName = "Stacionaran bicikl",
                            ExerciseTypeId = 1,
                            InsertDate = new DateTime(2022, 4, 20, 10, 45, 5, 196, DateTimeKind.Local).AddTicks(1994),
                            IsDeleted = false
                        },
                        new
                        {
                            ExerciseId = 47,
                            Description = "",
                            EnglishExerciseName = "Running",
                            ExerciseName = "Trčanje",
                            ExerciseTypeId = 1,
                            InsertDate = new DateTime(2022, 4, 20, 10, 45, 5, 196, DateTimeKind.Local).AddTicks(1997),
                            IsDeleted = false
                        },
                        new
                        {
                            ExerciseId = 48,
                            Description = "",
                            EnglishExerciseName = "Eliptical trainer",
                            ExerciseName = "Eliptični trenažer",
                            ExerciseTypeId = 1,
                            InsertDate = new DateTime(2022, 4, 20, 10, 45, 5, 196, DateTimeKind.Local).AddTicks(2002),
                            IsDeleted = false
                        },
                        new
                        {
                            ExerciseId = 49,
                            Description = "",
                            EnglishExerciseName = "Snatch",
                            ExerciseName = "Trzaj",
                            ExerciseTypeId = 1,
                            InsertDate = new DateTime(2022, 4, 20, 10, 45, 5, 196, DateTimeKind.Local).AddTicks(2005),
                            IsDeleted = false
                        },
                        new
                        {
                            ExerciseId = 50,
                            Description = "",
                            EnglishExerciseName = "Z press",
                            ExerciseName = "Z potisak",
                            ExerciseTypeId = 1,
                            InsertDate = new DateTime(2022, 4, 20, 10, 45, 5, 196, DateTimeKind.Local).AddTicks(2009),
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("PowerFit.Models.ExerciseCategoryRelationship", b =>
                {
                    b.Property<int>("ExerciseCategoryRelationshipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ExerciseId")
                        .HasColumnType("int");

                    b.Property<int>("SecondaryCategoryId")
                        .HasColumnType("int");

                    b.HasKey("ExerciseCategoryRelationshipId");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("SecondaryCategoryId");

                    b.ToTable("ExerciseCategoryRelationship");

                    b.HasData(
                        new
                        {
                            ExerciseCategoryRelationshipId = 1,
                            ExerciseId = 1,
                            SecondaryCategoryId = 9
                        },
                        new
                        {
                            ExerciseCategoryRelationshipId = 2,
                            ExerciseId = 1,
                            SecondaryCategoryId = 10
                        },
                        new
                        {
                            ExerciseCategoryRelationshipId = 3,
                            ExerciseId = 1,
                            SecondaryCategoryId = 11
                        },
                        new
                        {
                            ExerciseCategoryRelationshipId = 4,
                            ExerciseId = 2,
                            SecondaryCategoryId = 9
                        },
                        new
                        {
                            ExerciseCategoryRelationshipId = 5,
                            ExerciseId = 2,
                            SecondaryCategoryId = 10
                        },
                        new
                        {
                            ExerciseCategoryRelationshipId = 6,
                            ExerciseId = 2,
                            SecondaryCategoryId = 11
                        },
                        new
                        {
                            ExerciseCategoryRelationshipId = 7,
                            ExerciseId = 3,
                            SecondaryCategoryId = 9
                        },
                        new
                        {
                            ExerciseCategoryRelationshipId = 8,
                            ExerciseId = 3,
                            SecondaryCategoryId = 10
                        },
                        new
                        {
                            ExerciseCategoryRelationshipId = 9,
                            ExerciseId = 3,
                            SecondaryCategoryId = 11
                        },
                        new
                        {
                            ExerciseCategoryRelationshipId = 10,
                            ExerciseId = 4,
                            SecondaryCategoryId = 4
                        },
                        new
                        {
                            ExerciseCategoryRelationshipId = 12,
                            ExerciseId = 5,
                            SecondaryCategoryId = 4
                        },
                        new
                        {
                            ExerciseCategoryRelationshipId = 13,
                            ExerciseId = 6,
                            SecondaryCategoryId = 4
                        },
                        new
                        {
                            ExerciseCategoryRelationshipId = 14,
                            ExerciseId = 7,
                            SecondaryCategoryId = 13
                        },
                        new
                        {
                            ExerciseCategoryRelationshipId = 15,
                            ExerciseId = 8,
                            SecondaryCategoryId = 13
                        },
                        new
                        {
                            ExerciseCategoryRelationshipId = 16,
                            ExerciseId = 9,
                            SecondaryCategoryId = 13
                        },
                        new
                        {
                            ExerciseCategoryRelationshipId = 17,
                            ExerciseId = 10,
                            SecondaryCategoryId = 7
                        },
                        new
                        {
                            ExerciseCategoryRelationshipId = 18,
                            ExerciseId = 11,
                            SecondaryCategoryId = 7
                        },
                        new
                        {
                            ExerciseCategoryRelationshipId = 19,
                            ExerciseId = 12,
                            SecondaryCategoryId = 7
                        },
                        new
                        {
                            ExerciseCategoryRelationshipId = 20,
                            ExerciseId = 12,
                            SecondaryCategoryId = 2
                        },
                        new
                        {
                            ExerciseCategoryRelationshipId = 21,
                            ExerciseId = 12,
                            SecondaryCategoryId = 3
                        },
                        new
                        {
                            ExerciseCategoryRelationshipId = 22,
                            ExerciseId = 13,
                            SecondaryCategoryId = 6
                        },
                        new
                        {
                            ExerciseCategoryRelationshipId = 23,
                            ExerciseId = 14,
                            SecondaryCategoryId = 6
                        },
                        new
                        {
                            ExerciseCategoryRelationshipId = 24,
                            ExerciseId = 15,
                            SecondaryCategoryId = 6
                        },
                        new
                        {
                            ExerciseCategoryRelationshipId = 25,
                            ExerciseId = 15,
                            SecondaryCategoryId = 8
                        },
                        new
                        {
                            ExerciseCategoryRelationshipId = 26,
                            ExerciseId = 16,
                            SecondaryCategoryId = 2
                        },
                        new
                        {
                            ExerciseCategoryRelationshipId = 27,
                            ExerciseId = 16,
                            SecondaryCategoryId = 4
                        },
                        new
                        {
                            ExerciseCategoryRelationshipId = 28,
                            ExerciseId = 19,
                            SecondaryCategoryId = 2
                        },
                        new
                        {
                            ExerciseCategoryRelationshipId = 29,
                            ExerciseId = 17,
                            SecondaryCategoryId = 2
                        },
                        new
                        {
                            ExerciseCategoryRelationshipId = 30,
                            ExerciseId = 17,
                            SecondaryCategoryId = 7
                        },
                        new
                        {
                            ExerciseCategoryRelationshipId = 31,
                            ExerciseId = 18,
                            SecondaryCategoryId = 2
                        },
                        new
                        {
                            ExerciseCategoryRelationshipId = 32,
                            ExerciseId = 18,
                            SecondaryCategoryId = 7
                        },
                        new
                        {
                            ExerciseCategoryRelationshipId = 33,
                            ExerciseId = 20,
                            SecondaryCategoryId = 2
                        },
                        new
                        {
                            ExerciseCategoryRelationshipId = 34,
                            ExerciseId = 20,
                            SecondaryCategoryId = 3
                        },
                        new
                        {
                            ExerciseCategoryRelationshipId = 35,
                            ExerciseId = 20,
                            SecondaryCategoryId = 7
                        },
                        new
                        {
                            ExerciseCategoryRelationshipId = 36,
                            ExerciseId = 21,
                            SecondaryCategoryId = 2
                        },
                        new
                        {
                            ExerciseCategoryRelationshipId = 37,
                            ExerciseId = 21,
                            SecondaryCategoryId = 3
                        },
                        new
                        {
                            ExerciseCategoryRelationshipId = 38,
                            ExerciseId = 21,
                            SecondaryCategoryId = 7
                        },
                        new
                        {
                            ExerciseCategoryRelationshipId = 39,
                            ExerciseId = 22,
                            SecondaryCategoryId = 3
                        },
                        new
                        {
                            ExerciseCategoryRelationshipId = 40,
                            ExerciseId = 23,
                            SecondaryCategoryId = 5
                        },
                        new
                        {
                            ExerciseCategoryRelationshipId = 41,
                            ExerciseId = 24,
                            SecondaryCategoryId = 5
                        },
                        new
                        {
                            ExerciseCategoryRelationshipId = 42,
                            ExerciseId = 25,
                            SecondaryCategoryId = 5
                        },
                        new
                        {
                            ExerciseCategoryRelationshipId = 43,
                            ExerciseId = 30,
                            SecondaryCategoryId = 1
                        },
                        new
                        {
                            ExerciseCategoryRelationshipId = 44,
                            ExerciseId = 31,
                            SecondaryCategoryId = 1
                        },
                        new
                        {
                            ExerciseCategoryRelationshipId = 45,
                            ExerciseId = 32,
                            SecondaryCategoryId = 8
                        },
                        new
                        {
                            ExerciseCategoryRelationshipId = 46,
                            ExerciseId = 33,
                            SecondaryCategoryId = 8
                        },
                        new
                        {
                            ExerciseCategoryRelationshipId = 47,
                            ExerciseId = 34,
                            SecondaryCategoryId = 8
                        },
                        new
                        {
                            ExerciseCategoryRelationshipId = 48,
                            ExerciseId = 35,
                            SecondaryCategoryId = 8
                        },
                        new
                        {
                            ExerciseCategoryRelationshipId = 49,
                            ExerciseId = 36,
                            SecondaryCategoryId = 12
                        },
                        new
                        {
                            ExerciseCategoryRelationshipId = 50,
                            ExerciseId = 37,
                            SecondaryCategoryId = 12
                        },
                        new
                        {
                            ExerciseCategoryRelationshipId = 51,
                            ExerciseId = 38,
                            SecondaryCategoryId = 12
                        },
                        new
                        {
                            ExerciseCategoryRelationshipId = 52,
                            ExerciseId = 39,
                            SecondaryCategoryId = 13
                        },
                        new
                        {
                            ExerciseCategoryRelationshipId = 53,
                            ExerciseId = 40,
                            SecondaryCategoryId = 13
                        },
                        new
                        {
                            ExerciseCategoryRelationshipId = 54,
                            ExerciseId = 41,
                            SecondaryCategoryId = 13
                        },
                        new
                        {
                            ExerciseCategoryRelationshipId = 55,
                            ExerciseId = 42,
                            SecondaryCategoryId = 13
                        },
                        new
                        {
                            ExerciseCategoryRelationshipId = 56,
                            ExerciseId = 43,
                            SecondaryCategoryId = 13
                        },
                        new
                        {
                            ExerciseCategoryRelationshipId = 57,
                            ExerciseId = 44,
                            SecondaryCategoryId = 14
                        },
                        new
                        {
                            ExerciseCategoryRelationshipId = 58,
                            ExerciseId = 45,
                            SecondaryCategoryId = 14
                        },
                        new
                        {
                            ExerciseCategoryRelationshipId = 59,
                            ExerciseId = 46,
                            SecondaryCategoryId = 14
                        },
                        new
                        {
                            ExerciseCategoryRelationshipId = 60,
                            ExerciseId = 47,
                            SecondaryCategoryId = 14
                        },
                        new
                        {
                            ExerciseCategoryRelationshipId = 61,
                            ExerciseId = 48,
                            SecondaryCategoryId = 14
                        },
                        new
                        {
                            ExerciseCategoryRelationshipId = 62,
                            ExerciseId = 49,
                            SecondaryCategoryId = 13
                        },
                        new
                        {
                            ExerciseCategoryRelationshipId = 63,
                            ExerciseId = 50,
                            SecondaryCategoryId = 2
                        },
                        new
                        {
                            ExerciseCategoryRelationshipId = 64,
                            ExerciseId = 50,
                            SecondaryCategoryId = 7
                        });
                });

            modelBuilder.Entity("PowerFit.Models.ExerciseTag", b =>
                {
                    b.Property<int>("ExerciseTagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ExerciseTagId");

                    b.ToTable("ExerciseTag");

                    b.HasData(
                        new
                        {
                            ExerciseTagId = 1,
                            Name = "Vrat"
                        },
                        new
                        {
                            ExerciseTagId = 2,
                            Name = "Prsa"
                        },
                        new
                        {
                            ExerciseTagId = 3,
                            Name = "Ramena"
                        },
                        new
                        {
                            ExerciseTagId = 4,
                            Name = "Leđa"
                        },
                        new
                        {
                            ExerciseTagId = 5,
                            Name = "Trbušni mišići"
                        },
                        new
                        {
                            ExerciseTagId = 6,
                            Name = "Biceps"
                        },
                        new
                        {
                            ExerciseTagId = 7,
                            Name = "Triceps"
                        },
                        new
                        {
                            ExerciseTagId = 8,
                            Name = "Kvadriceps"
                        },
                        new
                        {
                            ExerciseTagId = 9,
                            Name = "Zadnja loža"
                        },
                        new
                        {
                            ExerciseTagId = 10,
                            Name = "Gluteus"
                        },
                        new
                        {
                            ExerciseTagId = 11,
                            Name = "List"
                        },
                        new
                        {
                            ExerciseTagId = 12,
                            Name = "Podlaktica"
                        });
                });

            modelBuilder.Entity("PowerFit.Models.FavoriteExercise", b =>
                {
                    b.Property<int>("FavoriteExerciseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ExerciseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("FavoriteExerciseId");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("UserId");

                    b.ToTable("FavoriteExercises");
                });

            modelBuilder.Entity("PowerFit.Models.PrimaryCategory", b =>
                {
                    b.Property<int>("PrimaryCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PrimaryCategoryId");

                    b.ToTable("PrimaryCategories");

                    b.HasData(
                        new
                        {
                            PrimaryCategoryId = 1,
                            Name = "Vježbe cijelog tijela"
                        },
                        new
                        {
                            PrimaryCategoryId = 2,
                            Name = "Gornji dio tijela"
                        },
                        new
                        {
                            PrimaryCategoryId = 3,
                            Name = "Donji dio tijela"
                        },
                        new
                        {
                            PrimaryCategoryId = 4,
                            Name = "Kardio vježbe"
                        });
                });

            modelBuilder.Entity("PowerFit.Models.PrimaryExerciseTagRelationship", b =>
                {
                    b.Property<int>("PrimaryExerciseTagRelationshipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ExerciseId")
                        .HasColumnType("int");

                    b.Property<int?>("ExerciseTagId")
                        .HasColumnType("int");

                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.HasKey("PrimaryExerciseTagRelationshipId");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("ExerciseTagId");

                    b.ToTable("PrimaryExerciseTagRelationship");

                    b.HasData(
                        new
                        {
                            PrimaryExerciseTagRelationshipId = 1,
                            ExerciseId = 1,
                            TagId = 8
                        },
                        new
                        {
                            PrimaryExerciseTagRelationshipId = 2,
                            ExerciseId = 1,
                            TagId = 10
                        },
                        new
                        {
                            PrimaryExerciseTagRelationshipId = 3,
                            ExerciseId = 2,
                            TagId = 8
                        },
                        new
                        {
                            PrimaryExerciseTagRelationshipId = 4,
                            ExerciseId = 2,
                            TagId = 10
                        },
                        new
                        {
                            PrimaryExerciseTagRelationshipId = 5,
                            ExerciseId = 3,
                            TagId = 10
                        },
                        new
                        {
                            PrimaryExerciseTagRelationshipId = 6,
                            ExerciseId = 3,
                            TagId = 8
                        },
                        new
                        {
                            PrimaryExerciseTagRelationshipId = 7,
                            ExerciseId = 3,
                            TagId = 9
                        },
                        new
                        {
                            PrimaryExerciseTagRelationshipId = 8,
                            ExerciseId = 4,
                            TagId = 4
                        },
                        new
                        {
                            PrimaryExerciseTagRelationshipId = 9,
                            ExerciseId = 5,
                            TagId = 4
                        },
                        new
                        {
                            PrimaryExerciseTagRelationshipId = 10,
                            ExerciseId = 6,
                            TagId = 4
                        },
                        new
                        {
                            PrimaryExerciseTagRelationshipId = 11,
                            ExerciseId = 7,
                            TagId = 9
                        },
                        new
                        {
                            PrimaryExerciseTagRelationshipId = 12,
                            ExerciseId = 7,
                            TagId = 10
                        },
                        new
                        {
                            PrimaryExerciseTagRelationshipId = 13,
                            ExerciseId = 7,
                            TagId = 8
                        },
                        new
                        {
                            PrimaryExerciseTagRelationshipId = 14,
                            ExerciseId = 8,
                            TagId = 8
                        },
                        new
                        {
                            PrimaryExerciseTagRelationshipId = 15,
                            ExerciseId = 8,
                            TagId = 10
                        },
                        new
                        {
                            PrimaryExerciseTagRelationshipId = 16,
                            ExerciseId = 8,
                            TagId = 9
                        },
                        new
                        {
                            PrimaryExerciseTagRelationshipId = 17,
                            ExerciseId = 9,
                            TagId = 9
                        },
                        new
                        {
                            PrimaryExerciseTagRelationshipId = 18,
                            ExerciseId = 9,
                            TagId = 10
                        },
                        new
                        {
                            PrimaryExerciseTagRelationshipId = 19,
                            ExerciseId = 9,
                            TagId = 4
                        },
                        new
                        {
                            PrimaryExerciseTagRelationshipId = 20,
                            ExerciseId = 10,
                            TagId = 7
                        },
                        new
                        {
                            PrimaryExerciseTagRelationshipId = 21,
                            ExerciseId = 11,
                            TagId = 7
                        },
                        new
                        {
                            PrimaryExerciseTagRelationshipId = 22,
                            ExerciseId = 12,
                            TagId = 7
                        },
                        new
                        {
                            PrimaryExerciseTagRelationshipId = 23,
                            ExerciseId = 12,
                            TagId = 2
                        },
                        new
                        {
                            PrimaryExerciseTagRelationshipId = 24,
                            ExerciseId = 12,
                            TagId = 3
                        },
                        new
                        {
                            PrimaryExerciseTagRelationshipId = 25,
                            ExerciseId = 13,
                            TagId = 6
                        },
                        new
                        {
                            PrimaryExerciseTagRelationshipId = 26,
                            ExerciseId = 14,
                            TagId = 6
                        },
                        new
                        {
                            PrimaryExerciseTagRelationshipId = 27,
                            ExerciseId = 15,
                            TagId = 6
                        },
                        new
                        {
                            PrimaryExerciseTagRelationshipId = 28,
                            ExerciseId = 15,
                            TagId = 12
                        },
                        new
                        {
                            PrimaryExerciseTagRelationshipId = 29,
                            ExerciseId = 16,
                            TagId = 3
                        },
                        new
                        {
                            PrimaryExerciseTagRelationshipId = 30,
                            ExerciseId = 17,
                            TagId = 3
                        },
                        new
                        {
                            PrimaryExerciseTagRelationshipId = 31,
                            ExerciseId = 18,
                            TagId = 3
                        },
                        new
                        {
                            PrimaryExerciseTagRelationshipId = 32,
                            ExerciseId = 19,
                            TagId = 3
                        },
                        new
                        {
                            PrimaryExerciseTagRelationshipId = 33,
                            ExerciseId = 20,
                            TagId = 2
                        },
                        new
                        {
                            PrimaryExerciseTagRelationshipId = 34,
                            ExerciseId = 21,
                            TagId = 2
                        },
                        new
                        {
                            PrimaryExerciseTagRelationshipId = 35,
                            ExerciseId = 21,
                            TagId = 3
                        },
                        new
                        {
                            PrimaryExerciseTagRelationshipId = 36,
                            ExerciseId = 22,
                            TagId = 2
                        },
                        new
                        {
                            PrimaryExerciseTagRelationshipId = 37,
                            ExerciseId = 23,
                            TagId = 5
                        },
                        new
                        {
                            PrimaryExerciseTagRelationshipId = 38,
                            ExerciseId = 24,
                            TagId = 5
                        },
                        new
                        {
                            PrimaryExerciseTagRelationshipId = 39,
                            ExerciseId = 25,
                            TagId = 5
                        },
                        new
                        {
                            PrimaryExerciseTagRelationshipId = 41,
                            ExerciseId = 30,
                            TagId = 1
                        },
                        new
                        {
                            PrimaryExerciseTagRelationshipId = 42,
                            ExerciseId = 31,
                            TagId = 1
                        },
                        new
                        {
                            PrimaryExerciseTagRelationshipId = 43,
                            ExerciseId = 32,
                            TagId = 12
                        },
                        new
                        {
                            PrimaryExerciseTagRelationshipId = 44,
                            ExerciseId = 33,
                            TagId = 12
                        },
                        new
                        {
                            PrimaryExerciseTagRelationshipId = 45,
                            ExerciseId = 34,
                            TagId = 12
                        },
                        new
                        {
                            PrimaryExerciseTagRelationshipId = 46,
                            ExerciseId = 35,
                            TagId = 12
                        },
                        new
                        {
                            PrimaryExerciseTagRelationshipId = 47,
                            ExerciseId = 36,
                            TagId = 11
                        },
                        new
                        {
                            PrimaryExerciseTagRelationshipId = 48,
                            ExerciseId = 37,
                            TagId = 11
                        },
                        new
                        {
                            PrimaryExerciseTagRelationshipId = 49,
                            ExerciseId = 38,
                            TagId = 11
                        },
                        new
                        {
                            PrimaryExerciseTagRelationshipId = 50,
                            ExerciseId = 39,
                            TagId = 4
                        },
                        new
                        {
                            PrimaryExerciseTagRelationshipId = 51,
                            ExerciseId = 39,
                            TagId = 8
                        },
                        new
                        {
                            PrimaryExerciseTagRelationshipId = 52,
                            ExerciseId = 39,
                            TagId = 10
                        },
                        new
                        {
                            PrimaryExerciseTagRelationshipId = 53,
                            ExerciseId = 39,
                            TagId = 12
                        },
                        new
                        {
                            PrimaryExerciseTagRelationshipId = 54,
                            ExerciseId = 39,
                            TagId = 9
                        },
                        new
                        {
                            PrimaryExerciseTagRelationshipId = 55,
                            ExerciseId = 40,
                            TagId = 3
                        },
                        new
                        {
                            PrimaryExerciseTagRelationshipId = 56,
                            ExerciseId = 40,
                            TagId = 4
                        },
                        new
                        {
                            PrimaryExerciseTagRelationshipId = 57,
                            ExerciseId = 40,
                            TagId = 10
                        },
                        new
                        {
                            PrimaryExerciseTagRelationshipId = 58,
                            ExerciseId = 40,
                            TagId = 8
                        },
                        new
                        {
                            PrimaryExerciseTagRelationshipId = 59,
                            ExerciseId = 41,
                            TagId = 4
                        },
                        new
                        {
                            PrimaryExerciseTagRelationshipId = 60,
                            ExerciseId = 41,
                            TagId = 8
                        },
                        new
                        {
                            PrimaryExerciseTagRelationshipId = 61,
                            ExerciseId = 41,
                            TagId = 10
                        },
                        new
                        {
                            PrimaryExerciseTagRelationshipId = 62,
                            ExerciseId = 41,
                            TagId = 11
                        },
                        new
                        {
                            PrimaryExerciseTagRelationshipId = 63,
                            ExerciseId = 42,
                            TagId = 3
                        },
                        new
                        {
                            PrimaryExerciseTagRelationshipId = 64,
                            ExerciseId = 42,
                            TagId = 4
                        },
                        new
                        {
                            PrimaryExerciseTagRelationshipId = 65,
                            ExerciseId = 42,
                            TagId = 10
                        },
                        new
                        {
                            PrimaryExerciseTagRelationshipId = 66,
                            ExerciseId = 42,
                            TagId = 8
                        },
                        new
                        {
                            PrimaryExerciseTagRelationshipId = 67,
                            ExerciseId = 43,
                            TagId = 3
                        },
                        new
                        {
                            PrimaryExerciseTagRelationshipId = 68,
                            ExerciseId = 43,
                            TagId = 4
                        },
                        new
                        {
                            PrimaryExerciseTagRelationshipId = 69,
                            ExerciseId = 43,
                            TagId = 10
                        },
                        new
                        {
                            PrimaryExerciseTagRelationshipId = 70,
                            ExerciseId = 43,
                            TagId = 8
                        });
                });

            modelBuilder.Entity("PowerFit.Models.SecondaryCategory", b =>
                {
                    b.Property<int>("SecondaryCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PrimaryCategoryId")
                        .HasColumnType("int");

                    b.HasKey("SecondaryCategoryId");

                    b.HasIndex("PrimaryCategoryId");

                    b.ToTable("SecondaryCategories");

                    b.HasData(
                        new
                        {
                            SecondaryCategoryId = 1,
                            Description = "",
                            Name = "Vrat",
                            PrimaryCategoryId = 2
                        },
                        new
                        {
                            SecondaryCategoryId = 2,
                            Description = "Sastoje se od 3 dijela(tzv. glave) - prednji, lateralni i stražnji.",
                            Name = "Ramena",
                            PrimaryCategoryId = 2
                        },
                        new
                        {
                            SecondaryCategoryId = 3,
                            Description = "Sastoje se od dva mišića - gornji dio (pectoralis minor) i donji dio (pectoralis major).",
                            Name = "Prsa",
                            PrimaryCategoryId = 2
                        },
                        new
                        {
                            SecondaryCategoryId = 4,
                            Description = "Najveća skupina mišiča u gornjem dijelu tijela.",
                            Name = "Leđa",
                            PrimaryCategoryId = 2
                        },
                        new
                        {
                            SecondaryCategoryId = 5,
                            Description = "Poznati kao 6-pack, ovi mišići dolaze do izražaja kod manjeg postotka tijelesne masnoće.",
                            Name = "Trbušni mišići",
                            PrimaryCategoryId = 2
                        },
                        new
                        {
                            SecondaryCategoryId = 6,
                            Description = "Dvoglavi mišić.",
                            Name = "Biceps",
                            PrimaryCategoryId = 2
                        },
                        new
                        {
                            SecondaryCategoryId = 7,
                            Description = "Troglavi mišić - čini 60% muskulature i gornjem dijelu ruke.",
                            Name = "Triceps",
                            PrimaryCategoryId = 2
                        },
                        new
                        {
                            SecondaryCategoryId = 8,
                            Description = "",
                            Name = "Podlaktica",
                            PrimaryCategoryId = 2
                        },
                        new
                        {
                            SecondaryCategoryId = 9,
                            Description = "Četveroglavi mišić na prednjem dijelu noge.",
                            Name = "Kvadriceps",
                            PrimaryCategoryId = 3
                        },
                        new
                        {
                            SecondaryCategoryId = 10,
                            Description = "Najveća mišićna skupina na tijelu",
                            Name = "Gluteus",
                            PrimaryCategoryId = 3
                        },
                        new
                        {
                            SecondaryCategoryId = 11,
                            Description = "Dvoglavi mišić na stražnjem dijelu noge.",
                            Name = "Zadnja loža",
                            PrimaryCategoryId = 3
                        },
                        new
                        {
                            SecondaryCategoryId = 12,
                            Description = "Mišić donjeg dijela noge.",
                            Name = "List",
                            PrimaryCategoryId = 3
                        },
                        new
                        {
                            SecondaryCategoryId = 13,
                            Description = "",
                            Name = "Cijelo tijelo",
                            PrimaryCategoryId = 1
                        },
                        new
                        {
                            SecondaryCategoryId = 14,
                            Description = "",
                            Name = "Kardio",
                            PrimaryCategoryId = 4
                        });
                });

            modelBuilder.Entity("PowerFit.Models.SecondaryExerciseTagRelationship", b =>
                {
                    b.Property<int>("SecondaryExerciseTagRelationshipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ExerciseId")
                        .HasColumnType("int");

                    b.Property<int?>("ExerciseTagId")
                        .HasColumnType("int");

                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.HasKey("SecondaryExerciseTagRelationshipId");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("ExerciseTagId");

                    b.ToTable("SecondaryExerciseTagRelationship");

                    b.HasData(
                        new
                        {
                            SecondaryExerciseTagRelationshipId = 1,
                            ExerciseId = 1,
                            TagId = 4
                        },
                        new
                        {
                            SecondaryExerciseTagRelationshipId = 2,
                            ExerciseId = 1,
                            TagId = 9
                        },
                        new
                        {
                            SecondaryExerciseTagRelationshipId = 3,
                            ExerciseId = 1,
                            TagId = 5
                        },
                        new
                        {
                            SecondaryExerciseTagRelationshipId = 4,
                            ExerciseId = 2,
                            TagId = 4
                        },
                        new
                        {
                            SecondaryExerciseTagRelationshipId = 5,
                            ExerciseId = 2,
                            TagId = 9
                        },
                        new
                        {
                            SecondaryExerciseTagRelationshipId = 6,
                            ExerciseId = 2,
                            TagId = 5
                        },
                        new
                        {
                            SecondaryExerciseTagRelationshipId = 7,
                            ExerciseId = 3,
                            TagId = 11
                        },
                        new
                        {
                            SecondaryExerciseTagRelationshipId = 8,
                            ExerciseId = 3,
                            TagId = 4
                        },
                        new
                        {
                            SecondaryExerciseTagRelationshipId = 9,
                            ExerciseId = 4,
                            TagId = 6
                        },
                        new
                        {
                            SecondaryExerciseTagRelationshipId = 10,
                            ExerciseId = 5,
                            TagId = 6
                        },
                        new
                        {
                            SecondaryExerciseTagRelationshipId = 11,
                            ExerciseId = 6,
                            TagId = 6
                        },
                        new
                        {
                            SecondaryExerciseTagRelationshipId = 12,
                            ExerciseId = 7,
                            TagId = 4
                        },
                        new
                        {
                            SecondaryExerciseTagRelationshipId = 13,
                            ExerciseId = 7,
                            TagId = 5
                        },
                        new
                        {
                            SecondaryExerciseTagRelationshipId = 14,
                            ExerciseId = 7,
                            TagId = 12
                        },
                        new
                        {
                            SecondaryExerciseTagRelationshipId = 15,
                            ExerciseId = 8,
                            TagId = 4
                        },
                        new
                        {
                            SecondaryExerciseTagRelationshipId = 16,
                            ExerciseId = 8,
                            TagId = 5
                        },
                        new
                        {
                            SecondaryExerciseTagRelationshipId = 17,
                            ExerciseId = 8,
                            TagId = 12
                        },
                        new
                        {
                            SecondaryExerciseTagRelationshipId = 18,
                            ExerciseId = 9,
                            TagId = 5
                        },
                        new
                        {
                            SecondaryExerciseTagRelationshipId = 19,
                            ExerciseId = 9,
                            TagId = 12
                        },
                        new
                        {
                            SecondaryExerciseTagRelationshipId = 20,
                            ExerciseId = 13,
                            TagId = 12
                        },
                        new
                        {
                            SecondaryExerciseTagRelationshipId = 21,
                            ExerciseId = 14,
                            TagId = 12
                        },
                        new
                        {
                            SecondaryExerciseTagRelationshipId = 22,
                            ExerciseId = 16,
                            TagId = 4
                        },
                        new
                        {
                            SecondaryExerciseTagRelationshipId = 23,
                            ExerciseId = 16,
                            TagId = 6
                        },
                        new
                        {
                            SecondaryExerciseTagRelationshipId = 24,
                            ExerciseId = 17,
                            TagId = 2
                        },
                        new
                        {
                            SecondaryExerciseTagRelationshipId = 25,
                            ExerciseId = 17,
                            TagId = 7
                        },
                        new
                        {
                            SecondaryExerciseTagRelationshipId = 26,
                            ExerciseId = 18,
                            TagId = 7
                        },
                        new
                        {
                            SecondaryExerciseTagRelationshipId = 27,
                            ExerciseId = 20,
                            TagId = 3
                        },
                        new
                        {
                            SecondaryExerciseTagRelationshipId = 28,
                            ExerciseId = 20,
                            TagId = 7
                        },
                        new
                        {
                            SecondaryExerciseTagRelationshipId = 29,
                            ExerciseId = 21,
                            TagId = 7
                        },
                        new
                        {
                            SecondaryExerciseTagRelationshipId = 30,
                            ExerciseId = 39,
                            TagId = 5
                        },
                        new
                        {
                            SecondaryExerciseTagRelationshipId = 31,
                            ExerciseId = 39,
                            TagId = 11
                        },
                        new
                        {
                            SecondaryExerciseTagRelationshipId = 32,
                            ExerciseId = 40,
                            TagId = 2
                        },
                        new
                        {
                            SecondaryExerciseTagRelationshipId = 33,
                            ExerciseId = 40,
                            TagId = 5
                        },
                        new
                        {
                            SecondaryExerciseTagRelationshipId = 34,
                            ExerciseId = 40,
                            TagId = 6
                        },
                        new
                        {
                            SecondaryExerciseTagRelationshipId = 35,
                            ExerciseId = 40,
                            TagId = 7
                        },
                        new
                        {
                            SecondaryExerciseTagRelationshipId = 36,
                            ExerciseId = 41,
                            TagId = 5
                        },
                        new
                        {
                            SecondaryExerciseTagRelationshipId = 37,
                            ExerciseId = 41,
                            TagId = 9
                        },
                        new
                        {
                            SecondaryExerciseTagRelationshipId = 38,
                            ExerciseId = 42,
                            TagId = 5
                        },
                        new
                        {
                            SecondaryExerciseTagRelationshipId = 39,
                            ExerciseId = 42,
                            TagId = 6
                        },
                        new
                        {
                            SecondaryExerciseTagRelationshipId = 40,
                            ExerciseId = 42,
                            TagId = 7
                        },
                        new
                        {
                            SecondaryExerciseTagRelationshipId = 41,
                            ExerciseId = 43,
                            TagId = 5
                        },
                        new
                        {
                            SecondaryExerciseTagRelationshipId = 42,
                            ExerciseId = 43,
                            TagId = 6
                        },
                        new
                        {
                            SecondaryExerciseTagRelationshipId = 43,
                            ExerciseId = 43,
                            TagId = 7
                        });
                });

            modelBuilder.Entity("PowerFit.Models.Type", b =>
                {
                    b.Property<int>("TypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TypeId");

                    b.ToTable("Types");

                    b.HasData(
                        new
                        {
                            TypeId = 1,
                            Description = "Vježbe kod kojih se koristi više skupina mišića.",
                            Name = "Kompaktna vježba"
                        },
                        new
                        {
                            TypeId = 2,
                            Description = "Vježbe gdje se primarno koristi jedan mišić.",
                            Name = "Izolacijska vježba"
                        },
                        new
                        {
                            TypeId = 3,
                            Description = "Vježbe gdje nema pokreta u zglobovima i gdje se mišić drži u istom položaju.",
                            Name = "Statička vježba"
                        });
                });

            modelBuilder.Entity("PowerFit.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CountryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailVerified")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HashedPassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telephone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PowerFit.Models.Exercise", b =>
                {
                    b.HasOne("PowerFit.Models.Type", "ExerciseType")
                        .WithMany("Exercises")
                        .HasForeignKey("ExerciseTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExerciseType");
                });

            modelBuilder.Entity("PowerFit.Models.ExerciseCategoryRelationship", b =>
                {
                    b.HasOne("PowerFit.Models.Exercise", "Exercise")
                        .WithMany("ExerciseCategoryRelationship")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PowerFit.Models.SecondaryCategory", "SecondaryCategory")
                        .WithMany("ExerciseCategoryRelationship")
                        .HasForeignKey("SecondaryCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("SecondaryCategory");
                });

            modelBuilder.Entity("PowerFit.Models.FavoriteExercise", b =>
                {
                    b.HasOne("PowerFit.Models.Exercise", "Exercise")
                        .WithMany("FavoriteExercise")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PowerFit.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PowerFit.Models.PrimaryExerciseTagRelationship", b =>
                {
                    b.HasOne("PowerFit.Models.Exercise", "Exercise")
                        .WithMany("PrimaryExerciseTagRelationship")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PowerFit.Models.ExerciseTag", "ExerciseTag")
                        .WithMany("PrimaryExerciseTagRelationship")
                        .HasForeignKey("ExerciseTagId");

                    b.Navigation("Exercise");

                    b.Navigation("ExerciseTag");
                });

            modelBuilder.Entity("PowerFit.Models.SecondaryCategory", b =>
                {
                    b.HasOne("PowerFit.Models.PrimaryCategory", "PrimaryCategory")
                        .WithMany("ExerciseCategories")
                        .HasForeignKey("PrimaryCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PrimaryCategory");
                });

            modelBuilder.Entity("PowerFit.Models.SecondaryExerciseTagRelationship", b =>
                {
                    b.HasOne("PowerFit.Models.Exercise", "Exercise")
                        .WithMany("SecondaryExerciseTagRelationship")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PowerFit.Models.ExerciseTag", "ExerciseTag")
                        .WithMany("SecondaryExerciseTagRelationship")
                        .HasForeignKey("ExerciseTagId");

                    b.Navigation("Exercise");

                    b.Navigation("ExerciseTag");
                });

            modelBuilder.Entity("PowerFit.Models.Exercise", b =>
                {
                    b.Navigation("ExerciseCategoryRelationship");

                    b.Navigation("FavoriteExercise");

                    b.Navigation("PrimaryExerciseTagRelationship");

                    b.Navigation("SecondaryExerciseTagRelationship");
                });

            modelBuilder.Entity("PowerFit.Models.ExerciseTag", b =>
                {
                    b.Navigation("PrimaryExerciseTagRelationship");

                    b.Navigation("SecondaryExerciseTagRelationship");
                });

            modelBuilder.Entity("PowerFit.Models.PrimaryCategory", b =>
                {
                    b.Navigation("ExerciseCategories");
                });

            modelBuilder.Entity("PowerFit.Models.SecondaryCategory", b =>
                {
                    b.Navigation("ExerciseCategoryRelationship");
                });

            modelBuilder.Entity("PowerFit.Models.Type", b =>
                {
                    b.Navigation("Exercises");
                });
#pragma warning restore 612, 618
        }
    }
}
